version: '3'
services:
  python:
    tty: true
    build: .
    volumes:
      - .:/myapp
      - huggingface-cache-volume:/root/.cache/huggingface
    ports:
      - 8888:8888

volumes:
  huggingface-cache-volume: